### ISSUE TITLE
Spectrum::ToTH1() leaks

### ISSUE THREAD

**Issue by plasorak** [CAFAnaFramework/CAFAnaCore#5]
I find this line quite confusing: https://github.com/CAFAnaFramework/CAFAnaCore/blob/05c635ca405c32e83c3fccea5dc376a9e76e62a2/CAFAna/Core/UtilsExt.cxx#L54
This means that the ownership of this pointer is delegated to the caller, which in the end is whoever does something like this:
```
Spectrum spectra = [...]
TH1D* histo = spectra.ToTH1(pot);
```
To me it's not clear that `ToTH1` should return a new pointer, and definitely not that I need to delete it.
Although here I'd suggest returning an `unique_ptr`, it's pretty clear doing so will break a vast amount of user code, so I don't have a good solution.

**Comment by cjbackhouse** [comment]
Yeah, this is by design. Or at least unfixable. We could add a comment spelling it out. The only real purpose to getting a TH1 from a spectrum is to plot it. And the way ROOT works, you're then pretty much required to leak it, otherwise it disappears from your canvas again. If you just want the bin contents, use the eigen interface. But ideally, most operations can be expressed on Spectrum objects themselves.

**Comment by plasorak** [comment]
I see, thanks, I didn't know about eigen, I'll have a look. I guess we can close this issue then.
